project:
  type: website

website:
  title: "Home"
  open-graph: true
  search: false
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: '#FAFBFD'
    right:
      - text: About
        href: about/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Publications
        menu:
          - text: Journal Articles
            href: publications/journal_articles/index.qmd
          - text: Conference Papers
            href: publications/conference_papers/index.qmd
          - text: Book Chapters
            href: publications/book_chapters/index.qmd
          - text: Working Papers
            href: publications/working_papers/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: Blog
        href: blog/index.qmd

format:
  html:
    theme: [cosmo, styles.scss]
